#!/bin/bash
#
# Scripted by FUF Nov 3, 2016
# This shell script detects a directory, retrieves the files from the directory and deletes it.
# Directories that include the initials plx will be skipped.

# log please
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>$PATHTOCONFIG/log-plex-retrieve.out 2>&1
# Everything below will go to the file 'log.out':

source local
  for Directory
  do
    pwd=`pwd`
    Loc=`dirname "$Directory"`
    Directorio=`basename $Directory`
    chown -R plex:wheel *
    chmod -R 777 *
    cd "$Loc"

    if `echo $Directorio | grep -q plx`

    then
      echo "$Directorio is a -plx protected folder"
    else
            if test -d $Directory
            then
                echo "$Directorio is a folder"
                cd "$Directory"
                plrename *
                rm -R sample
                cd subs
                plrename *
                mv 1*ng*.srt "$pwd"/"$Directorio"\.in\.srt
                mv 2*ng*.srt "$pwd"/"$Directorio"\.en\.srt
                mv 3*ng*.srt "$pwd"/"$Directorio"\.eng\.srt
                mv *nglish.srt "$pwd"/"$Directorio"\.srt
                mv *nglish*.srt "$pwd"/"$Directorio"\.english\.srt
                mv *.srt "$pwd"/
                mv *.idx "$pwd"/
                mv *.sub "$pwd"/
                cd "$pwd"
                cd "$Directory"
                rmdir subs
                rm *.nfo
                rm *.txt
                rm *.exe
                mv * ../
                cd "$pwd"
                rmdir "$Directorio"
            else
                echo "$Directorio is a file"
            fi
    fi
  done
