#!/bin/bash
#
# Scripted by FUF Nov 3, 2016
# This shell script removes the following characters from filenames and directories: space ( ) [ ] ' _ ending . ending -

# log please
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>$PATHTOCONFIG/log-plex-rename.out 2>&1
# Everything below will go to the file 'log.out':

  for OriginalFile
  do

    Location=`dirname "$OriginalFile"`
    FileName=`basename "$OriginalFile"`

    ShortName01=`echo $FileName | sed "s/[][(){}&= _']/./g"`
    ShortName02=`echo $ShortName01 | sed 's/\.\././g'`
    ShortName03=`echo $ShortName02 | sed 's/\.\././g'`
    ShortName04=`echo $ShortName03 | sed 's/\,\././g'`
    ShortName05=`echo $ShortName04 | sed 's/\.$//g'`
    ShortName06=`echo $ShortName05 | sed 's/-$//g'`
    ShortName07=`echo $ShortName06 | sed 's/\.$//g'`
    ShortName08=`echo $ShortName07 | sed 's/.*/\L&/g'`
    ShortName09=`echo $ShortName08 | sed 's/\.-\./-/g'`
    ShortName10=`echo $ShortName09 | sed 's/-\././g'`

    if [ $ShortName10 != "$FileName" ]
    then
      cd "$Location"
      mv "$FileName" "$ShortName10"
      echo "$FileName is now $ShortName10"
    fi

  done
